config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'codes/home'

  
  #get 'codes/new'

  #get 'codes/create'

  #get 'codes/destroy'

  #get 'codes/compile'

  resources :codes, only: [:home, :new, :create, :destroy, :compile, :download,:sendFile]
  get 'codes', to: "codes#home"
  root "codes#home"
  post 'codes/:id', to: 'codes#compile'
  post 'codes/download/:id', to: 'codes#sendFile'
  post 'codes/error/:id', to: 'codes#error'
  post 'codes/show/:id', to: 'codes#show'
  #post  'download/:id', to: 'download#sendFile'
  #get 'codes/:id', to: 'codes#compile'
  #get 'public/outputs/:output'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader
	validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  def home
      @codes = Code.all

   end
   
   def new
      @code = Code.new
   end
   
   def create
      @code = Code.new(code_params)
      
      if @code.save
        @code.update_attribute(:user, current_user.id)
         redirect_to codes_path, notice: "The code #{@code.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @code = Code.find(params[:id])
      @code.destroy
      redirect_to codes_path, notice:  "The code #{@code.name} has been deleted."
   end
   
   def compile
      code= Code.find(params[:id])
      fileLocation=code.attachment.to_s
      output = `g++ -o public/outputs/output#{code.id} #{Rails.root}/public#{fileLocation} 2>&1`

      if output.empty? 
        code.update_attribute(:is_compiled, true)
        code.update_attribute(:output,"output#{code.id}")
      else 
        code.update_attribute(:error,output)
      end 
         
    end

    def sendFile
      code = Code.find(params[:id])
      send_file("#{Rails.root}/public/outputs/#{code.output}",filename: "#{code.name}")
    end

    def error
      @code = Code.find(params[:id])

    end

    def show
      @code = Code.find(params[:id])
    end
   


   private
      def code_params
      params.require(:code).permit(:name, :attachment, :is_compiled, :output, :error, :user)
   end
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
	 def sendFile
      code = Code.find(params[:id])
      send_file("#{Rails.root}/public/outputs/#{code.output}",filename: "#{code.name}",type: "application")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/views/codes/compile.html.erb
<% controller.redirect_to root_path %>

app/views/codes/create.html.erb
<h1>Codes#create</h1>
<p>Find me in app/views/codes/create.html.erb</p>

app/views/codes/destroy.html.erb
<h1>Codes#destroy</h1>
<p>Find me in app/views/codes/destroy.html.erb</p>

app/views/codes/error.html.erb
<br />
 <%= link_to "Homepage", root_path, class: "btn btn-primary" %>
 <br />
<pre><%= @code.error%></pre>

app/views/codes/home.html.erb
<% if user_signed_in? %>
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />
<%= link_to "Homepage", root_path, class: "btn btn-primary" %>
<%= link_to "New Code", new_code_path, class: "btn btn-primary" %>
<%= link_to "log out", destroy_user_session_path, :method => :delete, class: "btn-primary" %> 
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @codes.each do |code| %>
         <% if code.user == current_user.id%>
         <tr>
            <td><%= code.name %></td>
            <td><%= link_to "Download code", code.attachment_url %></td>
            <td>
            	<% if code.is_compiled %>
           		 	<%= button_to "Download", "codes/download/#{code.id}" %>
           		<% else %>
           			Not compiled yet
           		<% end %>
            </td>
            <td>
            	<% if code.is_compiled %>
           		 	No errors
           		<% else %>
           			<%= button_to "Show Errors", "codes/error/#{code.id}" %>
           		<% end %>
            </td>
            <td> <%= button_to "Show Code", "codes/show/#{code.id}"%></td>
            <td><%= button_to "Delete",  code, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{code.name}?" %></td>
            <td><%if code.is_compiled %>           
              This file is already compiled
            <% else %>
             <%= button_to "Compile", code, method: :compile %>
             <% end %>
         </tr>
         <% end %>
      <% end %>
   </tbody>
   
</table>
<% else %>
  <p class="sign_in"> <%= link_to "login", new_user_session_path%> </p>
  <p class="sign_up"> <%= link_to "sign up", new_user_registration_path%> </p>
<% end %>

app/views/codes/new.html.erb
<% if !@code.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @code.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @code, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
<div class="navigation">
<%= link_to "Homepage", root_path, class: "btn btn-primary" %>
</div>

app/views/codes/show.html.erb
<pre><%= render :file => ("#{Rails.root}/public"+@code.attachment.to_s) %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kompilatoronline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  	<div class="container" style="padding-top:20px;">
    <%= yield %>
    </div>
  </body>
</html>